"""After Effects FX library: 50 finished, procedural effects as After Effects builders, ready to hand to Spine.

Rebuilt from a slot clip pair and a cel effect-pack reference (each matched frame by frame on measured size, colour and
timing, nothing traced), in two looks:
  - cel: flat toon / cel shading (target ring, sun rune, electric star and ring, fire rose, water impact and dome,
    whirlpool, pink burst, smoke puff, fireball, pot burst, rainbow burst, coin glow, reel fire, confetti,
    free-spins flash and sunburst)
  - realistic: the same effects driven by the cel comps' motion but made of CC0 photo / Kenney textures, plus 6 glow
    VFX (gl_*) and 8 element FX (el_*).

Data lives in ``ae_library/``: ``jsx/<builder>.jsx`` (each defines ``BUILD(V)`` that builds comp ``<comp>`` and returns
its JSON), the shared kits (``fxlib.jsx`` cel helpers, ``re_kit`` / ``gl_kit`` / ``el_kit`` texture helpers,
``times.jsx`` reference frame times), ``tex/`` (two hand-set ramps), ``textures/photo`` (CC0 / public-domain photos)
and ``library.json`` (one entry per effect: builder, version, comp, blend, loop, fps, frames, anchor, the entries it
``needs`` built first, whether it needs the texture folder, the Spine budget, notes).

Workflow: ``fetch_textures(dir)`` once (Kenney packs + the committed photos, processed exactly as the builders were
tuned), ``script([...], textures_dir)`` -> run the returned ``run_with`` with the After Effects MCP (``ae_run_script``)
in an open, saved project, then ``to_spine(name, aep=...)`` renders the comp and makes one skeleton per effect.
"""
from __future__ import annotations

import csv
import io
import json
import shutil
import urllib.request
import zipfile
from pathlib import Path

import numpy as np
from PIL import Image

LIB = Path(__file__).resolve().parent / "ae_library"
JSX = LIB / "jsx"
KENNEY = {
    "kenney_particle-pack": "https://kenney.nl/media/pages/assets/particle-pack/f8fe0f8cb8-1677578741/kenney_particle-pack.zip",
    "kenney_smoke-particles": "https://kenney.nl/media/pages/assets/smoke-particles/23249a0d35-1677695171/kenney_smoke-particles.zip",
}
# photos on black -> straight RGBA by unmultiplying black (the black point is a percentile of max(rgb)); the builders
# were tuned on exactly these, so keep the table if you add photos
UNMULT = {"smoke_01": 40, "smoke_02": 40, "smoke_03": 40, "smoke_04": 40, "water_01": 25, "water_02": 25,
          "sparks_02": 25, "fire_01": 25, "electric_01": 25, "lightning_01": 40, "lightning_02": 40, "bokeh_01": 25,
          "bokeh_02": 25, "explosion_02": 40}
OPAQUE = ["clay_01", "clay_02", "water_drop_01", "water_drop_02", "explosion_01", "explosion_03", "fire_05"]


def library() -> dict:
    return json.loads((LIB / "library.json").read_text())["effects"]


def listing(look: str = "", kind: str = "") -> list[dict]:
    """Short rows: name, look (cel | realistic), kind (hero | clip | glow | element), blend, loop, seconds, notes."""
    rows = []
    for n, e in library().items():
        if (look and e["look"] != look) or (kind and e.get("kind") != kind):
            continue
        rows.append({"name": n, "look": e["look"], "kind": e.get("kind"), "comp": e["comp"], "blend": e["blend"],
                     "loop": e["loop"], "seconds": round((e.get("frames") or 0) / float(e.get("fps") or 25), 2),
                     "needs": e["needs"], "textures": e["textures"], "notes": e["notes"][:160]})
    return rows


def build_order(names: list[str]) -> list[dict]:
    """The entries to build, dependencies first, each once."""
    lib, out, seen = library(), [], set()

    def visit(n, stack=()):
        if n in seen:
            return
        if n not in lib:
            raise KeyError(f"unknown effect {n!r}; ae_library() lists them")
        if n in stack:
            raise ValueError(f"dependency cycle at {n}")
        for d in lib[n]["needs"]:
            visit(d, stack + (n,))
        seen.add(n)
        out.append(lib[n])
    for n in names:
        visit(n)
    return out


def _js(s: str) -> str:
    return json.dumps(str(s).replace("\\", "/"))


def script(names: list[str], textures_dir: str = "", rebuild: bool = False, save_as: str = "") -> str:
    """ExtendScript that builds `names` (and what they need) in the OPEN After Effects project and returns a JSON list
    of {comp, width, height, fps, frames} (or {error}). Comps that already exist are kept unless rebuild=True.
    textures_dir: the folder made by fetch_textures (needed by every realistic / gl_ / el_ entry)."""
    steps = build_order(names)
    if any(e["textures"] for e in steps) and not textures_dir:
        raise ValueError("these effects use textures: run fetch_textures(<dir>) once and pass textures_dir=<dir>")
    tex = textures_dir.rstrip("/\\") + "/" if textures_dir else ""
    lines = [
        "// generated by claude_spine.ae_fx_library.script()",
        f"var FXLIB_DIR = {_js(str(JSX) + '/')};",
        f"var FXLIB_TEX = {_js(str(LIB / 'tex') + '/')};",
        f"var FXLIB_TEXTURES = {_js(tex)};",
        "(function () {",
        "  var OUT = [];",
        "  function has(n) { for (var i = 1; i <= app.project.numItems; i++) { var it = app.project.item(i);"
        " if (it instanceof CompItem && it.name === n) return true; } return false; }",
        "  if (FXLIB_TEXTURES && !new Folder(FXLIB_TEXTURES + 'kenney_particle-pack').exists)"
        " return '[{\"error\":\"textures not found in ' + FXLIB_TEXTURES + ' (run fetch_textures)\"}]';",
        "  $.evalFile(FXLIB_DIR + 'fxlib.jsx'); $.evalFile(FXLIB_DIR + 'times.jsx');",
    ]
    for e in steps:
        lines.append(f"  if ({'true' if rebuild else 'false'} || !has({_js(e['comp'])})) {{ try {{"
                     f" $.evalFile(FXLIB_DIR + {_js(e['builder'] + '.jsx')}); OUT.push(String(BUILD({int(e['version'])})));"
                     f" }} catch (err) {{ OUT.push('{{\"error\":' + JSON_q({_js(e['name'])} + ': ' + err.toString()"
                     f" + ' line ' + err.line) + '}}'); }} }} else OUT.push('{{\"comp\":{json.dumps(e['comp'])},\"kept\":true}}');")
    lines += [
        "  try { FX.cleanSolids(); } catch (x) {}",
        (f"  app.project.save(new File({_js(save_as)}));" if save_as else
         "  if (app.project.file) app.project.save();"),
        "  return '[' + OUT.join(',') + ']';",
        "  function JSON_q(s) { return '\"' + String(s).replace(/\\\\/g, '/').replace(/\"/g, \"'\") + '\"'; }",
        "})();",
    ]
    return "\n".join(lines) + "\n"


def write_script(names: list[str], out_dir: str, textures_dir: str = "", rebuild: bool = False,
                 save_as: str = "") -> dict:
    out = Path(out_dir).expanduser()
    out.mkdir(parents=True, exist_ok=True)
    tag = names[0] if len(names) == 1 else f"{names[0]}_and_{len(names) - 1}_more"
    f = out / f"fxlib_{tag}.jsx"
    f.write_text(script(names, textures_dir, rebuild, save_as), encoding="utf-8")
    steps = build_order(names)
    return {"script": str(f), "run_with": "return String($.evalFile(new File(" + _js(f) + ")));",
            "builds": [s["comp"] for s in steps], "comps": {n: library()[n]["comp"] for n in names},
            "next": "run `run_with` with the After Effects MCP's ae_run_script (the project must be saved: aerender "
                    "reads the file), then ae_library_to_spine(name, aep=<the .aep>)"}


# --------------------------------------------------------------------------------------------- textures
def unmultiply(rgb: np.ndarray, percentile: float) -> np.ndarray:
    """Photo on black (float 0..1 HxWx3) -> straight RGBA: lift the black point to the `percentile` of max(rgb),
    alpha = max channel, rgb / alpha."""
    bp = float(np.percentile(rgb.max(2), percentile))
    x = np.clip((rgb - bp) / max(1e-6, 1 - bp), 0, 1)
    a = x.max(2, keepdims=True)
    col = np.where(a > 1e-4, x / np.maximum(a, 1e-4), 0)
    return np.concatenate([col, a], 2)


def fetch_textures(dest: str, download: bool = True) -> dict:
    """Make the texture folder the realistic builders use: Kenney Particle Pack + Smoke Particles (CC0, downloaded
    from kenney.nl), the library's CC0 / public-domain photos, `ready/` (photos unmultiplied to RGBA, opaque ones as
    JPEG) and CREDITS. Idempotent: existing packs are not downloaded again."""
    d = Path(dest).expanduser()
    (d / "photo").mkdir(parents=True, exist_ok=True)
    (d / "ready").mkdir(exist_ok=True)
    got = {}
    for name, url in KENNEY.items():
        if (d / name).exists() and any((d / name).rglob("*.png")):
            got[name] = "present"
            continue
        if not download:
            got[name] = "missing (download=False)"
            continue
        req = urllib.request.Request(url, headers={"User-Agent": "claude-spine ae_fx_library"})
        data = urllib.request.urlopen(req, timeout=120).read()
        with zipfile.ZipFile(io.BytesIO(data)) as z:
            z.extractall(d / name)
        got[name] = f"downloaded {len(data) // 1024} KB"
    src = LIB / "textures"
    for p in (src / "photo").glob("*.jpg"):
        shutil.copy2(p, d / "photo" / p.name)
    shutil.copy2(src / "CREDITS_photos.csv", d / "CREDITS_photos.csv")
    for n, pct in UNMULT.items():
        rgb = np.asarray(Image.open(d / "photo" / f"{n}.jpg").convert("RGB"), np.float32) / 255
        Image.fromarray((unmultiply(rgb, pct) * 255).astype(np.uint8), "RGBA").save(d / "ready" / f"{n}.png")
    for n in OPAQUE:
        Image.open(d / "photo" / f"{n}.jpg").convert("RGB").save(d / "ready" / f"{n}.jpg", quality=92)
    rows = list(csv.reader(open(d / "CREDITS_photos.csv")))[1:]
    (d / "CREDITS.md").write_text(
        "# Texture credits (CC0 or public domain: free for commercial use, no attribution required)\n\n"
        "- Kenney Particle Pack + Smoke Particles, CC0 1.0, https://kenney.nl/assets/particle-pack , "
        "https://kenney.nl/assets/smoke-particles\n"
        f"- {len(rows)} photos (Openverse / rawpixel PD collection / Flickr / Wikimedia Commons), CC0 or Public Domain "
        "Mark: per-file title, author, licence and source page in CREDITS_photos.csv\n")
    return {"dir": str(d), "packs": got, "photos": len(rows), "ready": len(list((d / "ready").iterdir()))}


# --------------------------------------------------------------------------------------------- to Spine
def to_spine(name: str, out_dir: str, aep: str = "", frames_dir: str = "", max_size: int = 0, max_frames: int = 0,
             spine_project: bool = True) -> dict:
    """Render the effect's comp (aep) or read frames already rendered (frames_dir: TIFF premultiplied / PNG), and
    make ONE skeleton `fx_<name>` with one animation `<name>` on a bone `fx` at the origin: <out_dir>/<name>/ holds
    the source json + images/, export/ (json + atlas + pages) and, with the Spine CLI, the .spine project.
    Texture size / frame cap: the entry's budget (soft full-screen effects at half size, slow loops subsampled), else
    512 px (1024 for comps larger than 720 px) and every frame."""
    from . import ae_bridge, atlas, qa, spine_cli
    from .ae_vfx_director import import_optimized
    from .ir import Bone, new_skeleton
    from .project import Project

    e = library()[name]
    work = Path(out_dir).expanduser() / name
    shutil.rmtree(work, ignore_errors=True)
    work.mkdir(parents=True)
    if aep:
        fdir = work / "_frames"
        ae_bridge.render_comp(aep, e["comp"], fdir)
    elif frames_dir:
        fdir = Path(frames_dir).expanduser()
    else:
        raise ValueError("give aep=<saved .aep holding the comp> or frames_dir=<rendered frames>")
    frames = sorted(p for x in ("*.tif", "*.tiff", "*.png") for p in fdir.glob(x))
    if not frames:
        raise FileNotFoundError(f"no frames in {fdir}")
    first = ae_bridge.read_tiff(frames[0]) if frames[0].suffix.lower().startswith(".tif") else \
        np.asarray(Image.open(frames[0]))
    h, w = first.shape[:2]
    bud = e.get("spine", {})
    cap = max_size or bud.get("max_size") or (512 if max(w, h) <= 720 else 1024)
    size = min(cap, max(w, h))
    p = Project(work / f"fx_{name}.json", new_skeleton(f"fx_{name}", 1024, 1024))
    p.data.bones.append(Bone(name="fx", parent="root", x=0.0, y=0.0, length=10))
    mode = "additive" if e["blend"] == "additive" else "alpha"
    res = import_optimized(p, name, frames_dir=str(fdir), fps=float(e["fps"]), mode=mode,
                           blend="additive" if mode == "additive" else "normal", animation=name, parent="fx",
                           seq_mode="loop" if e["loop"] else "once", start=0.0, max_size=size,
                           max_frames=max_frames or bud.get("max_frames") or len(frames), feather=0.0,
                           target="desktop_preview", event="impact", style="premium")
    v = qa.validate(p.data)
    if not v["ok"]:
        raise RuntimeError(f"{name}: {v['errors']}")
    p.save()
    exp = work / "export"
    atlas.pack(p, exp, f"fx_{name}")
    out = {"name": name, "skeleton": str(p.path), "export": str(exp), "frames_in": len(frames),
           "frames_out": res.get("frames_out"), "texture": size, "blend": mode, "loop": e["loop"]}
    pages = sorted(exp.glob("*.png"))
    out["pages"] = len(pages)
    out["gpu_mb"] = round(sum(Image.open(x).width * Image.open(x).height * 4 for x in pages) / 2 ** 20, 1)
    if spine_project and spine_cli.available():
        r = spine_cli.make_project(str(p.path), str(work / f"fx_{name}.spine"))
        spine_cli.export_project(str(work / f"fx_{name}.spine"), str(exp), "json")
        out["spine"] = str(work / f"fx_{name}.spine")
        out["repairs"] = r["repairs"]
    if aep:
        shutil.rmtree(fdir, ignore_errors=True)
    return out
